spring.application.name=261CC3S2BSpringSigconBackend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.sql.init.mode=always
server.port=8080
jwt.secret=${TOKEN_JWT_SECRET}
logging.level.org.springframework.security=DEBUG
